CREATE TABLE company_user (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,

                              login varchar(255) NOT NULL,

                              CONSTRAINT company_user_pkey PRIMARY KEY (id),
                              CONSTRAINT company_user_uniq_login UNIQUE (login)
);